{% set version = "1.1.0" %}
{% set python_min = "3.10" %}

package:
  name: django-template-lsp
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/django-template-lsp/django_template_lsp-{{ version }}.tar.gz
  sha256: b883a3f769464233369e1a8c56d4fe6d00cc016e7476ac8c6fda71cedd3b7acf

build:
  entry_points:
    - djlsp = djlsp.cli:main
    - django-template-lsp = djlsp.cli:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - jedi
    - pygls
    - python >={{ python_min }}

test:
  imports:
    - djlsp
  commands:
    - pip check
    - djlsp --help
    - django-template-lsp --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fourdigits/django-template-lsp
  summary: Django template LSP
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
